commerce_payment.commerce_payment_gateway.plugin.qrcode_xem_payment_method:
  type: commerce_payment_gateway_configuration
  mapping:
    xem_public_key:
      type: string
      label: 'XEM Public key'
